version: "3.5"

services:
  backend:
    build: server
    ports:
      - "8000:8000"
    volumes:
      - /database
      - ./config:/config
      - ./server/docker-logs:/app/logs


  frontend:
    build: webapp
    ports:
      - "3000:3000"
    volumes:
      - ./config:/config
