# Generated by Django 3.2.4 on 2021-06-25 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_type', models.CharField(max_length=50)),
                ('os_name', models.CharField(max_length=50)),
                ('os_version', models.CharField(max_length=50)),
                ('os_architecture', models.CharField(max_length=50)),
                ('pc_name', models.CharField(max_length=50, unique=True)),
                ('domain', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('cpu_name', models.CharField(max_length=100)),
                ('cpu_clock', models.SmallIntegerField(null=True)),
                ('cpu_cores', models.SmallIntegerField(null=True)),
                ('cpu_threads', models.SmallIntegerField(null=True)),
                ('cpu_socket', models.CharField(max_length=10)),
                ('motherboard_manufacturer', models.CharField(max_length=50)),
                ('motherboard_product', models.CharField(max_length=100)),
                ('motherboard_serial', models.CharField(max_length=100)),
                ('ram', models.IntegerField(null=True)),
                ('ram0_Configuredclockspeed', models.IntegerField(null=True)),
                ('ram0_Capacity', models.IntegerField(null=True)),
                ('ram1_Configuredclockspeed', models.IntegerField(null=True)),
                ('ram1_Capacity', models.IntegerField(null=True)),
                ('ram2_Configuredclockspeed', models.IntegerField(null=True)),
                ('ram2_Capacity', models.IntegerField(null=True)),
                ('ram3_Configuredclockspeed', models.IntegerField(null=True)),
                ('ram3_Capacity', models.IntegerField(null=True)),
                ('videocard', models.CharField(max_length=100)),
                ('resX', models.IntegerField(null=True)),
                ('resY', models.IntegerField(null=True)),
                ('username', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=200)),
                ('serial_number', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=200)),
                ('updated', models.DateTimeField()),
                ('comment', models.TextField(null=True)),
                ('label', models.CharField(max_length=100)),
                ('form_factor', models.CharField(max_length=20)),
                ('monitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hardware.monitor')),
            ],
        ),
    ]
