# Generated by Django 3.2.9 on 2021-11-29 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('house', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet', models.CharField(max_length=50)),
                ('floor', models.SmallIntegerField()),
                ('description', models.TextField()),
                ('building', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='locations',
                    to='hardware.building'
                )),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('priority', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('location', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='employees',
                    to='hardware.location'
                )),
                ('role', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='users',
                    to='hardware.userrole'
                )),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_type', models.CharField(
                    choices=[('DESKTOP', 'Desktop'), ('LAPTOP', 'Laptop')],
                    default='DESKTOP',
                    max_length=50
                )),
                ('os_name', models.CharField(max_length=50, null=True)),
                ('os_architecture',
                 models.CharField(choices=[('x64', 'X64'), ('x32', 'X32')], max_length=50, null=True)),
                ('cpu_name', models.CharField(max_length=100, null=True)),
                ('cpu_clock', models.SmallIntegerField(null=True)),
                ('cpu_cores', models.SmallIntegerField(null=True)),
                ('cpu_threads', models.SmallIntegerField(null=True)),
                ('videocard_name', models.CharField(max_length=100, null=True)),
                ('videocard_memory', models.SmallIntegerField(null=True)),
                ('ram', models.FloatField(null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('domain', models.CharField(max_length=50, null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('serial_number', models.CharField(max_length=50, null=True, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(null=True)),
                ('label', models.CharField(max_length=100, null=True)),
                ('form_factor',
                 models.CharField(choices=[('ATX', 'Atx'), ('mATX', 'Matx')], default='ATX', max_length=20)),
                ('location', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='computers',
                    to='hardware.location'
                )),
                ('user', models.OneToOneField(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='computer',
                    to='hardware.user'
                )),
            ],
        ),
    ]
