# Generated by Django 3.2.7 on 2021-09-19 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('clock', models.SmallIntegerField()),
                ('cores', models.SmallIntegerField()),
                ('threads', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50, null=True)),
                ('architecture', models.CharField(choices=[('x64', 'X64'), ('x32', 'X32')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Videocard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('memory', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_type', models.CharField(choices=[('DESKTOP', 'Desktop'), ('LAPTOP', 'Laptop')], default='DESKTOP', max_length=50)),
                ('ram', models.IntegerField(null=True)),
                ('pc_name', models.CharField(max_length=50, unique=True)),
                ('domain', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('username', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=200)),
                ('serial_number', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('label', models.CharField(max_length=100)),
                ('form_factor', models.CharField(default='ATX', max_length=20)),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hardware.cpu')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hardware.os')),
                ('videocard', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hardware.videocard')),
            ],
        ),
    ]
