# Generated by Django 3.2.9 on 2021-12-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='floor',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('street', 'house')},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('building', 'cabinet')},
        ),
    ]
