# Generated by Django 3.2.7 on 2021-09-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='form_factor',
            field=models.CharField(choices=[('ATX', 'Atx'), ('mATX', 'Matx')], default='ATX', max_length=20),
        ),
    ]
