# Generated by Django 3.2.9 on 2021-12-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hardware', '0002_auto_20211201_1639'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='ComputerUser',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='user',
        ),
        migrations.AddField(
            model_name='computer',
            name='user',
            field=models.ManyToManyField(null=True, to='hardware.User'),
        ),
    ]
