# Generated by Django 3.2.9 on 2021-12-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hardware', '0002_auto_20211201_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('roles', models.ManyToManyField(to='hardware.UserRole')),
            ],
        ),
        migrations.RemoveField(
            model_name='computer',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='computer',
            name='users',
            field=models.ManyToManyField(related_name='computers', to='hardware.ComputerUser'),
        ),
    ]
