# Generated by Django 3.2.4 on 2021-06-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hardware', '0002_alter_pc_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pc',
            name='serial_number',
            field=models.IntegerField(),
        ),
    ]
