# Generated by Django 3.2.7 on 2021-09-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_alter_pc_form_factor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='os',
            unique_together={('name', 'architecture', 'version')},
        ),
    ]
