# Generated by Django 3.2.7 on 2021-09-19 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_alter_os_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='timezone',
        ),
        migrations.AlterField(
            model_name='pc',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pc',
            name='cpu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hardware.cpu'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='domain',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pc',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pc',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pc',
            name='os',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hardware.os'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pc',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pc',
            name='videocard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hardware.videocard'),
        ),
    ]
