# Generated by Django 3.2.7 on 2021-09-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_auto_20210919_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='os',
            name='name',
            field=models.CharField(choices=[('Windows', 'Win')], max_length=50),
        ),
    ]
