# Generated by Django 3.2.7 on 2021-09-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0005_alter_os_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pc',
            old_name='pc_name',
            new_name='name',
        ),
    ]
