# Generated by Django 3.2.7 on 2021-09-23 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0006_rename_pc_name_pc_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='os',
            unique_together={('name', 'architecture')},
        ),
        migrations.RemoveField(
            model_name='os',
            name='version',
        ),
    ]
