# Generated by Django 3.2.7 on 2021-09-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0008_alter_os_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='serial_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
