# Generated by Django 3.2.7 on 2021-09-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0009_alter_pc_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='serial_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
