# Generated by Django 3.2.7 on 2021-09-27 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0011_auto_20210927_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computer', to='hardware.user'),
        ),
    ]
