name: Webapp build

on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'webapp/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: 16.3
      - run: npm install
        working-directory: webapp
      - run: npm run build
        working-directory: webapp
