name: Webapp build

on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'webapp/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build webapp
        run: docker build webapp/ -f webapp/dockerfile.build -t ${{ secrets.CI_WEBAPP_TAG }}
      - name: Run container
        run: docker run -v `pwd`/config:/config ${{ secrets.CI_WEBAPP_TAG }}
